name: release

on:
  pull_request:
    types: [ closed ]
    branches:
      - 'main'

jobs:
  auto_publish:
    runs-on: ubuntu-latest
    env:
      FILE_PATH: README.md
    steps:
      - name: Filter from dependabot
        if: startsWith(github.head_ref, 'dependabot/')
        run: |
          echo "::notice This pull request is from dependabot. This workflow is will be skipped."
          exit 1

      - name: Checkout code
        if: github.event.pull_request.merged == true
        uses: actions/checkout@v4

      - name: update README.md
        if: github.event.pull_request.merged == true
        run: |
          VERSION_NAME="${{ github.event.pull_request.head.ref }}"
          
          echo "\`$VERSION_NAME\`" > temp.txt
          tail -n +2 "$FILE_PATH" >> temp.txt
          mv temp.txt "$FILE_PATH"

      - name: Commit changes
        if: github.event.pull_request.merged == true
        run: |
          git config --local user.email "${{ github.event.pull_request.user.email }}"
          git config --local user.name "${{ github.event.pull_request.user.name }}"
          git add "$FILE_PATH"
          git commit -m "(bot)Update the title of README.md with the version name."
          git push

      - name: Create tag by branch name
        if: github.event.pull_request.merged == true
        run: |
          git tag "${{ github.event.pull_request.head.ref }}"
          git push origin "${{ github.event.pull_request.head.ref }}"

      - name: Publish release
        if: github.event.pull_request.merged == true
        id: open-pr
        run: |
          gh release create "${{ github.event.pull_request.head.ref }}" --generate-notes --verify-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
