name: release

on:
  pull_request:
    types: [ closed ]
    branches:
      - 'main'

jobs:
  auto_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        if: github.event.pull_request.merged == true
        uses: actions/checkout@v3

      - name: Create tag by branch name
        run: |
          git tag "${{ github.event.pull_request.head.ref }}"
          git push origin "${{ github.event.pull_request.head.ref }}"

      - name: Publish release
        if: github.event.pull_request.merged == true
        id: open-pr
        run: |
          gh release create "${{ github.event.pull_request.head.ref }}" --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
