name: update README.md

on:
  push:
    branches:
      - 'deploy/**'

jobs:
  update_readme:
    runs-on: ubuntu-latest
    env:
      FILE_PATH: README.md
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update README.md
        run: |
          VERSION_NAME=${GITHUB_REF_NAME##*/}
          
          echo "\`$VERSION_NAME\`" > temp.txt
          tail -n +2 "$FILE_PATH" >> temp.txt
          mv temp.txt "$FILE_PATH"

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "${{ github.event.head_commit.author.email }}"
          git config --local user.name "${{ github.event.head_commit.author.name }}"
          git add "$FILE_PATH"
          git commit -m "(bot)Update the title of README.md with the version name."
          git push
