name: update README.md

on:
  push:
    branches:
      - 'deploy/**'

jobs:
  update_readme:
    runs-on: ubuntu-latest
    env:
      FILE_PATH: README.md
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version
        id: version_name
        run: |
          VERSION_NAME=${GITHUB_REF_NAME##*/}
          echo "value=$VERSION_NAME" >> $GITHUB_OUTPUT

      - name: Check already updated.
        run: |
          CURRENT_VERSION_NAME=$(head -n 1 $FILE_PATH)
          if [[ "\`${{ steps.version_name.outputs.value }}\`" = "$CURRENT_VERSION_NAME" ]]; then
            echo "::notice::Version name is already updated.This workflow is will be skipped."
            exit 0
          fi

      - name: Update README.md
        run: |
          echo "\`${{ steps.version_name.outputs.value }}\`" > temp.txt
          tail -n +2 "$FILE_PATH" >> temp.txt
          mv temp.txt "$FILE_PATH"

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "${{ github.event.head_commit.author.email }}"
          git config --local user.name "${{ github.event.head_commit.author.name }}"
          git add "$FILE_PATH"
          git commit -m "(bot)Update the title of README.md with the version name."
          git push
